### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lustrike** [kevindoveton/carpc#1]
Hi Kevin,
I'm Ciro, I'm 25 and I'm from Italy. Searching on internet I find out your car pc project. I'm very interested in it and I would try it. I downloaded the code from github but I can't compile and run it. I'm using Microsoft Visual Studio and it returns me some errors (I think due to some missing libraries).

Can you help me?

Thank you very much,
Ciro

**Comment by kevindoveton** [comment]
Hi Ciro, 

I last worked on this about 3 years ago and never really finished this project, it ended up being a much bigger task than I first imagined it to be. When I was working on it, I believe I was using Ubuntu, and I believe some of the requirements (bluez, ofono) are only available on linux platforms.

It might be worth checking out to see if any other projects have popped up since then. If I was to do this again I would probably use something like Electron/node.js rather than Qt.

Kevin

**Comment by lustrike** [comment]
Thank you, for your answer. I understand you, a project like this is a bomb that explode when you start thinking what you can do.
Nervertheless I'll try to make it working.

Ciro
